### ISSUE TITLE
Titanium 3.5.0 64bit support?

### ISSUE THREAD

**Issue by kosso** [viezel/TiSocial.Framework#109]
Hi there!

Have you been able to get this running on the Ti 3.5.0 Alpha? By February, all modules need to be updated for 64bit support.

See: http://www.appcelerator.com/blog/2014/11/alpha-version-of-titanium-sdk-64-bit-support-now-available

**Comment by caspahouzer** [comment]
Seems not to be 64 bit: dk.napp.social:1.7.7@project armv7 i386

**Comment by sukima** [comment]
Does commit 6683224e35f618435cd6aac550b24c4c25f71391 and 73295e8e1d5b1f69721be3b8efddcdf67b15f3e1 fix this? According to the change log it suggests this issue is now fixed... again.

> ***v1.7.8***
>
> * Added support for 64-bit. Previous attempt was incorrect.

No release has been offered yet. We have only 4 days left to submit apps with 64bit support meaning if there isn't a release ASAP then every app that uses this module is :poop: up a creak in **four days**!

**Comment by caspahouzer** [comment]
https://github.com/viezel/TiSocial.Framework/blob/master/dist/dk.napp.social-iphone-1.7.10.zip

is 64bit
